name: Test
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./setup-java
        with:
          version: 23
      - uses: ./setup-java
        with:
          version: 5
      - uses: ./setup-java
        with:
          version: 17
      - run: env
